In [58]:
import json
import pandas as pd
import numpy as np

In [59]:
data = []
with open('results.jsonl') as f:
    for l in f:
        res = json.loads(l)
        data.append(res)

In [60]:
df = pd.DataFrame(data)
df = df.astype({'example_id': np.int})

/var/folders/s3/mfdghj353t1_wq7s9l3x0jym0000gn/T/ipykernel_44873/603266161.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  df = df.astype({'example_id': np.int})

In [61]:
df

    example_id         volume     ref_volume          a          b           c
0         1149  176481.667361  112504.295311  35.332031  23.554688  101.250000
1         1237  141612.976773   93759.482822  28.847656  28.847656   81.250000
2        15179  206383.346294  138236.665187  29.761719  29.761719  111.250000
3        17356  186284.517657  165309.677124  31.796875  26.640625  105.000000
4        17703  298375.868466  182285.655098  38.472656  38.472656   96.250000
5         1866   97783.841831   79512.283392  34.546875  21.199219   63.749951
6         1985  168127.707460  136419.572372  30.656250  25.546875  102.500000
7         2306  218192.601196  123123.903313  40.480469  25.417969  101.250000
8        26897   99869.104872  151270.276286  40.828125  13.347656   87.500008
9        26996  230499.964308  188048.718309  31.277344  31.277344  112.500000
10       29188  302042.922104  178402.270360  36.626953  36.626953  107.500000
11       29658   95554.535656  134246.287193  31.066406  15.062500   97.500000
12        3080  177417.089045  126487.008247  28.574219  28.574219  103.750000
13        3085  201798.475623  110651.271345  32.949219  32.949219   88.750135
14        3246  118162.779775  138600.799084  32.695312  18.164062   95.000000
15       32517  202134.594658  136279.113331  31.066406  31.066406  100.000000
16       33462  154837.055033  116961.533203  27.625000  25.187500  106.250000
17       33574  265850.628024  181833.319988  41.613281  29.050781  105.000000
18       33589  219144.380309  138149.692879  44.890625  25.898438   90.000000
19       35757  138445.492002  105661.539059  48.011719  16.945312   81.250000
20       36615  187591.669505  152778.793163  38.597656  27.300781   85.000000
21       38978  288209.455655  230185.036387  36.640625  36.640625  102.500000
22        4042  300603.283791  186452.807388  38.597656  37.656250   98.750000
23       41392  308210.603711  147144.915700  39.101562  39.101562   96.250000
24       41395  135738.369896   88947.101612  27.412109  27.412109   86.250000
25       41474  130959.564850  154708.625164  32.976562  18.058594  105.000000
26       41680  234887.182997  145125.099144  44.925781  32.210938   77.500000
27       42750  157441.514087  126103.993835  34.734375  24.046875   90.000000
28        4373   58635.737789   51897.441998  24.476562  16.945312   67.500000
29       44861  163775.944929  119617.115536  28.880859  28.880859   93.750000
30       45487   77740.106765   93312.107606  34.013672  15.873047   68.750000
31       48663  103288.506843  155892.312298  29.841797  15.373047  107.500000
32       50409  110841.861918  109115.151486  31.839844  19.271484   86.250000
33       52238  108327.614017   74252.265930  24.062500  24.921875   86.250000
34        5236  128112.636997  130834.804896  50.070312  27.923828   43.750004
35        6364  161753.662972  200456.666436  36.011719  19.720703  108.750000
36        7561  236232.049520  212965.842590  58.101562  18.058594  107.500000
37        7701  219174.039827  125302.959995  38.597656  30.125000   90.000000

In [63]:
ref_df = pd.read_excel('../data/do projektow.xlsx')
ref_df = ref_df.iloc[1:]
ref_df = ref_df.T.reset_index(drop=True).T
ref_df.rename(columns={x: str(x) for x in ref_df.columns}, inplace=True)
ref_df = ref_df[~pd.isna(ref_df['0'])]
ref_df = ref_df.astype({'0': np.int})
ref_df
results_df = df.merge(ref_df, how='left', left_on='example_id', right_on='0')

/var/folders/s3/mfdghj353t1_wq7s9l3x0jym0000gn/T/ipykernel_44873/656985606.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ref_df = ref_df.astype({'0': np.int})

In [64]:
results_df

,example_id,volume,ref_volume,a,b,c,0,1,2,3,...,36,37,38,39,40,41,42,43,44,45
0,1149,176481.667361,112504.295311,35.332031,23.554688,101.250000,1149,2019,2018-11-26,x,...,CAP,NaN,NaN,CAPCVP,NaN,NaN,"CAP, CVP","1149 2018 11 26 A AVTKP.nii, 1149 2018 11 26 A...",podwójna segmentacja,NaN
1,1237,141612.976773,93759.482822,28.847656,28.847656,81.250000,1237,2019,2018-11-22,x,...,CAPCUP,NaN,NaN,CVP,NaN,NaN,NaN,"1237 2018 11 22 A AVTKP.nii, 1237 2018 11 22 A...","na A jeden label do usunięcia, nie ma przegląd...",NaN
2,15179,206383.346294,138236.665187,29.761719,29.761719,111.250000,15179,2019,2019-04-01,x,...,CVP,NaN,NaN,CVP,NaN,NaN,NaN,NaN,na B label do usunięcia,NaN
3,17356,186284.517657,165309.677124,31.796875,26.640625,105.000000,17356,2019,2019-03-18,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,na A jeden label do usunięcia,NaN
4,17703,298375.868466,182285.655098,38.472656,38.472656,96.250000,17703,2019,2019-03-13,x,...,CVP,NaN,NaN,CVP,NaN,NaN,NaN,NaN,na A i B jeden label do usunięcia,NaN
5,1866,97783.841831,79512.283392,34.546875,21.199219,63.749951,1866,2019,2018-12-05,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,"1866 2018 12 05 A AVTKP.nii, 1866 2018 12 05 A...",NaN,"brak faz w srii A, rodzilczość"
6,1985,168127.707460,136419.572372,30.656250,25.546875,102.500000,1985,2019,2018-12-13,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,"1985 2018 12 13 A AVTKP.nii, 1985 2018 12 13 A...","na A jeden label do usunięcia, 2 segmntacj po,...",NaN
7,2306,218192.601196,123123.903313,40.480469,25.417969,101.250000,2306,2018,2017-10-20,x,...,CVP,NaN,NaN,CVP,NaN,NaN,CVP,NaN,NaN,NaN
8,26897,99869.104872,151270.276286,40.828125,13.347656,87.500008,26897,2019,2018-11-14,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
9,26996,230499.964308,188048.718309,31.277344,31.277344,112.500000,26996,2019,2019-04-19,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
10,29188,302042.922104,178402.270360,36.626953,36.626953,107.500000,29188,2019,2019-06-21,x,...,CVP,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
11,29658,95554.535656,134246.287193,31.066406,15.062500,97.500000,29658,2019,2019-05-07,x,...,CVP,NaN,NaN,CVP,NaN,NaN,CVP,NaN,NaN,NaN
12,3080,177417.089045,126487.008247,28.574219,28.574219,103.750000,3080,2019,2018-11-21,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,fatalna rozdzielczość (4.5mm),NaN
13,3085,201798.475623,110651.271345,32.949219,32.949219,88.750135,3085,2018,2017-07-13,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
14,3246,118162.779775,138600.799084,32.695312,18.164062,95.000000,3246,2019,2018-12-05,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,fatalna rozdzielczość (2.5mm),NaN
15,32517,202134.594658,136279.113331,31.066406,31.066406,100.000000,32517,2019,2019-06-17,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,"są 3 badania w dwóch katalogach, obrysoane jes...",NaN
16,33462,154837.055033,116961.533203,27.625000,25.187500,106.250000,33462,2019,2019-05-14,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
17,33574,265850.628024,181833.319988,41.613281,29.050781,105.000000,33574,2019,2019-05-02,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
18,33589,219144.380309,138149.692879,44.890625,25.898438,90.000000,33589,2019,2019-07-02,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,brak mat dla A,NaN
19,35757,138445.492002,105661.539059,48.011719,16.945312,81.250000,35757,2018,2018-02-28,x,...,NaN,NaN,NaN,Native,NaN,NaN,NaN,NaN,brak innych serii B,NaN
20,36615,187591.669505,152778.793163,38.597656,27.300781,85.000000,36615,2019,2019-07-26,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
21,38978,288209.455655,230185.036387,36.640625,36.640625,102.500000,38978,2019,2019-07-25,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
22,4042,300603.283791,186452.807388,38.597656,37.656250,98.750000,4042,2019,2018-12-19,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,kora i rdzeń rozrysowane osobno,NaN
23,41392,308210.603711,147144.915700,39.101562,39.101562,96.250000,41392,2018,2018-07-31,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
24,41395,135738.369896,88947.101612,27.412109,27.412109,86.250000,41395,2018,2018-07-27,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,na B jeden label do usunięcia,NaN
25,41474,130959.564850,154708.625164,32.976562,18.058594,105.000000,41474,2018,2018-08-27,x,...,CVP,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
26,41680,234887.182997,145125.099144,44.925781,32.210938,77.500000,41680,2018,2018-08-17,x,...,CVP,NaN,NaN,CVP,NaN,NaN,CVP,NaN,NaN,NaN
27,42750,157441.514087,126103.993835,34.734375,24.046875,90.000000,42750,2018,2018-07-23,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
28,4373,58635.737789,51897.441998,24.476562,16.945312,67.500000,4373,2019,2018-12-20,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
29,44861,163775.944929,119617.115536,28.880859,28.880859,93.750000,44861,2018,2018-09-21,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
30,45487,77740.106765,93312.107606,34.013672,15.873047,68.750000,45487,2019,2019-06-25,x,...,CVP,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
31,48663,103288.506843,155892.312298,29.841797,15.373047,107.500000,48663,2018,2018-10-09,x,...,CVP,NaN,NaN,CVP,NaN,NaN,NaN,NaN,brak statystyki na B,NaN
32,50409,110841.861918,109115.151486,31.839844,19.271484,86.250000,50409,2019,2019-10-15,x,...,CVP,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
33,52238,108327.614017,74252.265930,24.062500,24.921875,86.250000,52238,2019,2019-09-30,x,...,CAP,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN
34,5236,128112.636997,130834.804896,50.070312,27.923828,43.750004,5236,2019,2018-12-20,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,na A i B jeden label do usunięcia,NaN
35,6364,161753.662972,200456.666436,36.011719,19.720703,108.750000,6364,2019,2019-01-10,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,na A i B jeden label do usunięcia,NaN
36,7561,236232.049520,212965.842590,58.101562,18.058594,107.500000,7561,2019,2019-02-06,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,na A i B jeden label do usunięcia,NaN
37,7701,219174.039827,125302.959995,38.597656,30.125000,90.000000,7701,2018,2017-10-30,x,...,NaN,NaN,NaN,CVP,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
results_df.to_excel('experiment_results.xlsx')